spring:
  application:
    name: auth-service
    #env파일 불러오기
  config:
    import: optional:file:auth-service/.env[.properties]
  #    db config
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#jwt
jwt:
  secret:
    key: ${JWT_SECRET_KEY}

#uereka client enable : false
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
#    유레카 클라이언트가 통신할때 필요한 유레카 서버 주소
    service-url:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT}/eureka/
#    enabled: false   # 유레카 클라이언트 비활성화

server:
  port: ${SERVER_PORT}
logging:
  level:
    org.springframework.security: DEBUG
# 문서화
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs      # 기본값이라 안 써도 되지만 명시해도 OK
  swagger-ui:
    enabled: true
    path: /swagger-ui       # 접속 URL: http://localhost:포트/swagger-ui
    display-request-duration: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
