spring:
  application:
    name: auth-service
    #env?? ????
  config:
    import: optional:file:auth-service/.env[.properties]
  #    db config
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#    client:
#      service-url:
#        defaultZone: http://localhost:8761/eureka/

#jwt
jwt:
  secret:
    key: ${JWT_SECRET_KEY}

#uereka client enable : false
eureka:
  client:
    enabled: false
server:
  port: 19090
logging:
  level:
    org.springframework.security: DEBUG
