spring:
  application:
    name: fastline-hub
  profiles:
    active: local
  config:
    import: optional:file:./hub-service/.env.dev[.properties]
  data:
    redis:
      host: localhost
      port: 6379
     # password: yourpassword
  cache:
    type: redis
  # 공통 JPA/Flyway/시간대
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update     # 스키마는 Flyway가 관리, 운영 습관: validate 고정
    properties:
      hibernate:
        format_sql: true
        # dialect는 Spring Boot가 드라이버로 자동 감지하므로 생략 가능(명시해도 무방)
        # dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-zone: Asia/Seoul

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
